server:
  port: 8082

spring:
  application:
    name: spring-cloud-client
  profiles:
    active: dev
#
#  config:
#    import: configserver:http://localhost:8888

management:
  endpoints:
    web:
      exposure:
        include: "refresh"
